### PR TITLE
fix some compiler warnings

### LINKED ISSUE #218: MSVC warnings at levels 3 and 4
Visual Studio 2022 Preview (v17.1.0-pre.2.0) building BLAKE3 1.3.0 for x64 emits the following narrowing warnings with warning level /W3:

```
S:\BLAKE3\c\blake3_avx512.c(1050): warning C4244: 'function': conversion from 'uint64_t' to 'int', possible loss of data
S:\BLAKE3\c\blake3_avx2.c(222): warning C4244: 'function': conversion from 'uint64_t' to 'int', possible loss of data
S:\BLAKE3\c\blake3_sse41.c(445): warning C4244: 'function': conversion from 'uint64_t' to 'int', possible loss of data
S:\BLAKE3\c\blake3_sse2.c(451): warning C4244: 'function': conversion from 'uint64_t' to 'int', possible loss of data
```

They are from passing `uint64_t counter` to intrinsics `_mm512_set1_epi32`, `_mm256_set1_epi32`, `_mm_set1_epi32`, `_mm_set1_epi32` which are prototyped to take an `int`.

While probably harmless it raises concerns for a reader like me that there might be something subtly off deep inside the vendored library as it pops up as part of my project build.

Some additional warnings manifest at /W4:
```
S:\BLAKE3\c\blake3_avx512.c(471): warning C4057: 'function': 'const char *' differs in indirection to slightly different base types from 'const uint8_t *'
S:\BLAKE3\c\blake3_avx512.c(727): warning C4057: 'function': 'const char *' differs in indirection to slightly different base types from 'const uint8_t *'
S:\BLAKE3\c\blake3_avx512.c(1040): warning C4057: 'function': 'const char *' differs in indirection to slightly different base types from 'const uint8_t *'
S:\BLAKE3\c\blake3_avx2.c(211): warning C4057: 'function': 'const char *' differs in indirection to slightly different base types from 'const uint8_t *'
S:\BLAKE3\c\blake3_sse41.c(432): warning C4057: 'function': 'const char *' differs in indirection to slightly different base types from 'const uint8_t *'
S:\BLAKE3\c\blake3_sse2.c(83): warning C4244: 'function': conversion from 'const int' to 'short', possible loss of data
S:\BLAKE3\c\blake3_sse2.c(438): warning C4057: 'function': 'const char *' differs in indirection to slightly different base types from 'const uint8_t *'
```
These are all from calls to `_mm_prefetch` and `_mm_set1_epi16`, which has prototypes taking `char const*` and `short` correspondingly.

### PR DESCRIPTION
**Pull request by sneves**
Fixes #218

### CODE REVIEW

File: c/blake3_avx2.c [hunk 1]
```diff
@@ -219,14 +219,15 @@ INLINE void load_counters(uint64_t counter, bool increment_counter,
...
   __m256i carry = _mm256_cmpgt_epi32(_mm256_xor_si256(add1, _mm256_set1_epi32(0x80000000)), 
                                      _mm256_xor_si256(   l, _mm256_set1_epi32(0x80000000)));
-  __m256i h = _mm256_sub_epi32(_mm256_set1_epi32(counter >> 32), carry);
+  __m256i h = _mm256_sub_epi32(_mm256_set1_epi32((int32_t)(counter >> 32)), carry);
   *out_lo = l;
   *out_hi = h;
 }
 
+static
 void blake3_hash8_avx2(const uint8_t *const *inputs, size_t blocks,
```
Comment (oconnor663) [inline c/blake3_avx2.c:231]: I think I put the `blake3_` prefix on these because I needed them to be non-static for some reason. But I can't remember what it was anymore :p
